### ISSUE TITLE
Add headless Chrome

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/diffbrowsers#11]
For many views such as modified glyphs, we don't care how it renders on different browsers. We just want to know what has changed. By using  headless Chrome, we can take screenshots for these views much quicker. It would also make the tool useable to folks who don't have a BrowserStack account.

cc @davelab6

**Comment by davelab6** [comment]
This will be elite :) Thanks!

**Comment by m4rc1e** [comment]
Closing since we'll get this sorted in https://github.com/googlefonts/fontdiffenator/pull/16#issuecomment-417637025 with fewer dependencies.
